added  security
RCherniavskiy/Online_Book_store pull request #10
Opened 2024-03-27 12:35 UTC by RCherniavskiy

2024-03-27 16:52 UTC, MAMentorFX requested changes

2024-03-27 16:52 UTC, MAMentorFX commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/07-assign-roles-to-users.yaml
end line . also insert it everywhere else

2024-03-27 16:52 UTC, MAMentorFX commented on src/main/java/book_store/controller/AuthController.java
>  }
Spring security does /login and /registration for, you dont need this methods

2024-03-28 11:47 UTC, kozhukhovsky approved these changes

2024-03-28 15:25 UTC, merged