added testBookCategory
RCherniavskiy/Online_Book_store pull request #17
Opened 2024-04-27 14:49 UTC by RCherniavskiy

2024-04-27 15:36 UTC, olekskov requested changes

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/BookControllerTest.java
> +        }
containsAll() should work here and will be much shorter (if you have proper equals of course)

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/BookControllerTest.java
> +        Assertions.assertEquals(expectedBook.getIsbn(), actualBook.getIsbn());
EqualsBuilder or implementing equals in model will allow to get rid of each field comparison

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/BookControllerTest.java
> +                .setPrice(requestDto.getPrice());
what is sense of having 2 identical dtos? you may omit expected and use requestDto as reference

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/BookControllerTest.java
> +        EqualsBuilder.reflectionEquals(expected,actual,"id");
why check author separately if you check it during reflectionEquals?

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/BookControllerTest.java
> +    }
Why you created book? You don't use it further.
Also would be nice to recheck DB state, if book was really deleted.
If your controller has code "return new ResponseEntity(NO_CONTENT);" this test will pass

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/BookControllerTest.java
> +                .andExpect(status().isOk());
again, nobody knows after this test if book was updated or not. Only response status is checked what means nearly nothing

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/BookControllerTest.java
> +}
empty line in the end of file

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/controller/CategoryControllerTest.java
> +}
empty line

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/service/BookServiceImplTest.java
> +}
again

2024-04-27 15:36 UTC, olekskov commented on src/test/java/book_store/service/CategoryServiceImplTest.java
> +}
recheck all files please

2024-04-28 14:26 UTC, Rommelua approved these changes

2024-04-29 06:22 UTC, merged