added readme
RCherniavskiy/Online_Book_store pull request #19
Opened 2024-05-22 16:27 UTC by RCherniavskiy

2024-05-23 09:21 UTC, Elena-Bruyako requested changes
Good job! Let's improve your readme file

2024-05-23 09:21 UTC, Elena-Bruyako commented on README.md
> +# Online Book Store Project API README
```suggestion
# Online Book Store Project API
```

2024-05-23 09:21 UTC, Elena-Bruyako commented on README.md
> +- **JWT (JSON Web Token):** Ensures secure user authentication.
Also, you can add Docker, Lombok, Hibernate, MySQL version, Java version

2024-05-23 09:21 UTC, Elena-Bruyako commented on README.md
> +
It's better to add Models and relations diagram.
In addition, describe Controllers endpoints will be good

2024-05-23 09:21 UTC, Elena-Bruyako commented on README.md
> +## Postman Collection
Add access to the API by Swagger

2024-05-27 13:07 UTC, okuzan approved these changes
Good job

2024-05-27 13:07 UTC, okuzan commented on README.md
> +If you encounter any problems while setting up or running the project, please contact the developers.
```suggestion
If you encounter any problems while setting up or running the project, please contact me.
```

2024-05-27 13:07 UTC, okuzan commented on README.md
> +I would like to express my gratitude to the Java Mentors at MateAcademy for their guidance and support.
```suggestion
I would like to express my gratitude to the Java Mentors at Mate Academy for their guidance and support.
```
🤝

2025-04-05 15:27 UTC, merged